# Generated by Django 4.2.6 on 2023-10-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCategories', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('ItemPhoto', models.ImageField(upload_to='')),
                ('ItemPrice', models.IntegerField()),
                ('ItemBacketCount', models.IntegerField()),
                ('ItemText', models.TextField()),
                ('Item', models.BooleanField(null=True)),
                ('ItemCategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.categories')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': [-1],
            },
        ),
    ]
